### ISSUE TITLE
Handle conversation button clicks after a conversation has ended

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#151]
This is the stacktrace from the error.
```
[2017-01-11T21:37:02.278Z] INFO: POST /slack/receive 200 0 - 26.778 ms
c:\Users\michael.beemer\Documents\GitHub\davis-server-V2\node_modules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (c:\Users\michael.beemer\Documents\GitHub\davis-server-V2\node_modules\botkit\lib\SlackBot.js:616:84)
    at Object.__dirname.Botkit.botkit.trigger (c:\Users\michael.beemer\Documents\GitHub\davis-server-V2\node_modules\botkit\lib\CoreBot.js:972:49)
    at c:\Users\michael.beemer\Documents\GitHub\davis-server-V2\node_modules\botkit\lib\CoreBot.js:1076:32
```

**Comment by dyladan** [comment]
So what do i have to do to reproduce this? Ask about problems, wait for davis to stop listening, then click a button?

**Comment by dyladan** [comment]
is this in dev, or just filter?

**Comment by beeme1mr** [comment]
@dyladan  filters, not sure about dev.

**Comment by dyladan** [comment]
well i'm not sure where it was introduced but it definitely isn't happening as of bc28ff0
