### ISSUE TITLE
Unhandled rejection TypeError when launching davis

### ISSUE THREAD

**Issue by mvlintho** [Dynatrace/davis-server#275]
Had a working davis setup but wanted to do an update;

steps:
1. service davis stop
2. npm update
3. service davis start

Actual result when launching it manually:

[root@davis davis]# NODE_ENV=production node index.js
Unhandled rejection TypeError: logger.setLevel is not a function
    at Object.<anonymous> (/opt/davis/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:26:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/davis/node_modules/natural/lib/natural/index.js:81:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/davis/node_modules/@dynatrace/davis/lib/classes/Utils/TextHelpers.js:4:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Am I missing something, or did something break?

Also noticed a dependency of bluebird which i've installed via npm.

**Comment by beeme1mr** [comment]
@mvlintho Thanks for reporting.  We'll look into this.

**Comment by dyladan** [comment]
Able to reproduce on a clean install with node 6. Updating the natural dependency from `^0.4.0` to `^0.5.0` fixed the issue. Release will be out soon

**Comment by beeme1mr** [comment]
@mvlintho v0.19.1 was release to resolve this issue.  Could you please run an NPM update?

**Comment by mvlintho** [comment]
New release fixed it!
Thank you for the fast feedback.
